CREATE TABLE Count(
    reg_id INTEGER NOT NULL DEFAULT 10101010,
    ll_reg INTEGER NOT NULL DEFAULT 10000000
);



CREATE TABLE Revenue(
    RTO VARCHAR(6) NOT NULL,
    Date DATETIME NOT NULL, 
    SRevenue FLOAT NOT NULL,
    VRevenue Float NOT NULL
);


CREATE TABLE RCReg(
    reg_id INTEGER NOT NULL PRIMARY KEY DEFAULT 10101010,
    RTO VARCHAR(6) NOT NULL,
    Chassis VARCHAR(20) NOT NULL,
    Engine VARCHAR(20) NOT NULL,
    Owner VARCHAR(20) NOT NULL,
    Address VARCHAR(30) NOT NULL,
    Mobile INTEGER NOT NULL,
    Manufacturer VARCHAR(20) NOT NULL,
    Model VARCHAR(20) NOT NULL,
    Color VARCHAR(10) NOT NULL,
    Class VARCHAR(10) NOT NULL,
    DOR DATETIME NOT NULL,
    Approved INTEGER NOT NULL,
    Vahicle_no VARCHAR(10) NOT NULL 
);

CREATE TABLE LLReg(
    reg_id INTEGER NOT NULL PRIMARY KEY,
    RTO VARCHAR(6) NOT NULL,
    Pincode INTEGER NOT NULL,
    Name VARCHAR(20) NOT NULL,
    DOB DATE NOT NULL,
    Gender VARCHAR(5) NOT NULL,
    Age INTEGER NOT NULL,
    Mail VARCHAR(20) DEFAULT NULL,
    Mobile INTEGER NOT NULL,
    Address VARCHAR(30) NOT NULL,
    Class VARCHAR(10) NOT NULL,
    Approved INTEGER NOT NULL,
    DOA DATETIME NOT NULL
);

CREATE TABLE DLReg(
    LLno INTEGER,
    DLno VARCHAR(20) DEFAULT NULL,
    Validity DATETIME,
    DOA DATETIME NOT NULL,
    Flag INTEGER NOT NULL,
    Status INTEGER NOT NULL,
    CONSTRAINT LLNO FOREIGN KEY(LLno) REFERENCES LLReg(reg_id)
);

CREATE TABLE Total(
    date DATETIME NOT NULL,
    RTO VARCHAR(10) NOT NULL,
    LLapplications INTEGER NOT NULL DEFAULT 0,
    DLapplications INTEGER NOT NULL DEFAULT 0,
    RCapplications INTEGER NOT NULL DEFAULT 0 
);

CREATE TABLE Users(
    username VARCHAR(20) NOT NULL,
    passwd VARCHAR(20) NOT NULL
);

CREATE TABLE Admin(
    username VARCHAR(20) NOT NULL,
    passwd VARCHAR(20) NOT NULL
);
